// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72SnRrFL8Dk9_JISZCpfZSYpVmxwZR8A',
    appId: '1:304419306153:web:99d1be3b910fe4041d07b8',
    messagingSenderId: '304419306153',
    projectId: 'zodiac-ed89d',
    authDomain: 'zodiac-ed89d.firebaseapp.com',
    storageBucket: 'zodiac-ed89d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNq66TUAAyTezwFnyk2_p23tNRA1Rtr4E',
    appId: '1:304419306153:android:626b05994a84a1a71d07b8',
    messagingSenderId: '304419306153',
    projectId: 'zodiac-ed89d',
    storageBucket: 'zodiac-ed89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxLc0opREZa06BE7Z2o6RM33M8-rat8l0',
    appId: '1:304419306153:ios:1e64f9a09c4fe8441d07b8',
    messagingSenderId: '304419306153',
    projectId: 'zodiac-ed89d',
    storageBucket: 'zodiac-ed89d.firebasestorage.app',
    iosBundleId: 'com.example.project11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxLc0opREZa06BE7Z2o6RM33M8-rat8l0',
    appId: '1:304419306153:ios:1e64f9a09c4fe8441d07b8',
    messagingSenderId: '304419306153',
    projectId: 'zodiac-ed89d',
    storageBucket: 'zodiac-ed89d.firebasestorage.app',
    iosBundleId: 'com.example.project11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC72SnRrFL8Dk9_JISZCpfZSYpVmxwZR8A',
    appId: '1:304419306153:web:e96b4b02edaf8e601d07b8',
    messagingSenderId: '304419306153',
    projectId: 'zodiac-ed89d',
    authDomain: 'zodiac-ed89d.firebaseapp.com',
    storageBucket: 'zodiac-ed89d.firebasestorage.app',
  );
}
